FROM alpine:3.19

RUN mkdir /var/log/remotelogs

RUN  apk update \
  && apk add rsyslog \
  && rm -rf /var/cache/apk/*

ADD config/rsyslog/rsyslog.conf /etc/rsyslog.conf

EXPOSE 514 514/udp
EXPOSE 50514

ENTRYPOINT [ "rsyslogd", "-n" ]