# Use Alpine Linux as the base image
FROM alpine:3.19

LABEL maintainer="UAREVIEWS"

# Install MariaDB from the Alpine repositories
RUN apk add --no-cache mariadb mariadb-client mariadb-server-utils
RUN mysql_install_db --user=mysql

VOLUME /data

# Create a new directory for MariaDB to store database files
ENTRYPOINT [ "mysqld_safe", "--datadir=/data" ]

# Expose the port MariaDB is reachable on
EXPOSE 3306