FROM alpine

# Instale o Nginx
RUN apk update && \
    apk add nginx

# Expor a porta 80 para acesso externo
EXPOSE 80

RUN rm /etc/nginx/nginx.conf

# Comando para iniciar o Nginx em primeiro plano
CMD ["nginx", "-g", "daemon off;"]
