FROM alpine:3.19

# Instale o Nginx
RUN apk update && \
    apk add nginx

# Expor a porta 80 para acesso externo
EXPOSE 80

# Comando para iniciar o Nginx em primeiro plano
CMD ["nginx", "-g", "daemon off;"]
