apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  master.cnf: |
    [mariadb]
    log-bin
    log-basename=master
    server-id=1
    binlog-format=row

  slave.cnf: |
    [mariadb]
    server-id=2
    replicate-do-db=mydb

  master.sql: |
    CREATE USER 'repl'@'%' IDENTIFIED BY 'replpassword';
    GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';
    FLUSH PRIVILEGES;
    CREATE DATABASE mydb;

  slave.sql: |
    CHANGE MASTER TO 
      MASTER_HOST='mariadb-master',
      MASTER_USER='repl',
      MASTER_PASSWORD='replpassword',
      MASTER_LOG_FILE='master-bin.000001',
      MASTER_LOG_POS=0;
    START SLAVE;
