apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
  namespace: uareviews
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mariadb
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mariadb
    role: slave
