apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: uareviews
data:
  nginx.conf: |
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        server {
            listen 80 default_server;
            server_name landingpage.uareviews.k3s;
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }