apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: uareviews
data:
  sentinel.conf: |
    port 26379
    dir /tmp
    sentinel monitor mymaster redis-svc.uareviews.svc.cluster.local 6379 1
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 10000
    sentinel parallel-syncs mymaster 1
