apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-dep
  namespace: uareviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis
        image: registry.deti/uareviews/redis:1.0.0

        ports:
        - containerPort: 6379

        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD

        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf

      volumes:
      - name: redis-config
        configMap:
          name: redis-slave-config
