apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-dep
  namespace: uareviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: registry.deti/uareviews/rsyslog:1.0.0
        ports:
        - containerPort: 50514 # Adjust the port number as needed
