apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-ha-svc
  name: redis-ha-svc
spec:
  ports:
  - port: 6379
    name: master
  - port: 26379
    name: sentinel
  clusterIP: None
  selector:
    app: redis-master
